services:
  # Backend API Service
  - type: web
    name: maia-chess-backend
    env: python
    runtime: python-3.10.12
    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free

  # Frontend Static Site
  - type: static
    name: maia-chess-frontend
    buildCommand: cd frontend && npm ci && npm run build
    publishPath: ./frontend/dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        value: https://maia-chess-backend.onrender.com