services:
  # Backend API Service
  - type: web
    name: maia-chess-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: ENVIRONMENT
        value: production
    plan: free

  # Frontend Web Application
  - type: web
    name: maia-chess-frontend
    env: node
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_URL
        value: https://maia-chess-backend.onrender.com
    plan: free